from __future__ import annotations

from typing import Any


SWARM_MODES = [
    "fastest_build",
    "balanced",
    "high_quality",
    "documentation_heavy",
    "research_planning",
    "massive_codebase",
    "manager_decides",
]

SWARM_AGGRESSIVENESS = ["small", "medium", "large", "maximum", "manager_decides"]
DOCS_DEPTH = ["minimal", "standard", "detailed", "publishable"]
TESTING_DEPTH = ["minimal", "standard", "extensive", "release_grade"]
SWARM_RISK_LEVELS = ["low", "medium", "high"]


AGENT_ARCHETYPE_CATALOG: list[dict[str, Any]] = [
    {
        "name": "manager",
        "purpose": "Own the project strategy, route tasks, and make swarm decisions.",
        "default_guidelines": "Do not write broad code changes directly when worker delegation is cleaner.",
        "default_tools_json": ["planning", "queue_management", "approval_routing"],
        "default_permissions_json": {"spawn_agents": True, "approve_required": False},
        "spawn_triggers_json": ["Always present as the user-facing coordinator."],
        "retirement_triggers_json": ["Retires only when the project is archived or deleted."],
        "risk_profile": "medium",
    },
    {
        "name": "planner",
        "purpose": "Break goals into milestones, tasks, and path-safe work packages.",
        "default_guidelines": "Prefer non-overlapping scopes and explicit validation steps.",
        "default_tools_json": ["task_planning", "doc_updates"],
        "default_permissions_json": {"write_docs": True},
        "spawn_triggers_json": ["Scope is unclear", "Milestones need restructuring"],
        "retirement_triggers_json": ["Architecture is stable and milestone routing is clear."],
        "risk_profile": "low",
    },
    {
        "name": "architect",
        "purpose": "Choose architecture, boundaries, and subsystem ownership.",
        "default_guidelines": "Set path ownership early when the codebase is large or parallelism is high.",
        "default_tools_json": ["repo_mapping", "design_notes"],
        "default_permissions_json": {"write_architecture_notes": True},
        "spawn_triggers_json": ["Architecture is unclear", "Subsystem ownership is risky"],
        "retirement_triggers_json": ["Path strategy and architecture are accepted."],
        "risk_profile": "medium",
    },
    {
        "name": "frontend",
        "purpose": "Build and polish user-facing interface flows.",
        "default_guidelines": "Preserve established design language and keep UI paths isolated.",
        "default_tools_json": ["ui_editing", "component_work"],
        "default_permissions_json": {"write_src": True},
        "spawn_triggers_json": ["UI-heavy features are in scope"],
        "retirement_triggers_json": ["Targeted UI slice is implemented and reviewed."],
        "risk_profile": "medium",
    },
    {
        "name": "backend",
        "purpose": "Implement server-side behavior, APIs, and domain logic.",
        "default_guidelines": "Prefer explicit tests and avoid touching unrelated UI files.",
        "default_tools_json": ["api_editing", "tests"],
        "default_permissions_json": {"write_server": True},
        "spawn_triggers_json": ["Backend or API work is in scope"],
        "retirement_triggers_json": ["Backend slice is merged and validated."],
        "risk_profile": "medium",
    },
    {
        "name": "feature",
        "purpose": "Ship a bounded product slice end to end.",
        "default_guidelines": "Own a narrow vertical slice with strict allowed paths.",
        "default_tools_json": ["feature_work", "tests"],
        "default_permissions_json": {"write_feature_paths": True},
        "spawn_triggers_json": ["Independent feature slices exist"],
        "retirement_triggers_json": ["Assigned slice is complete and handed off to review."],
        "risk_profile": "medium",
    },
    {
        "name": "integration",
        "purpose": "Own connector and cross-system integration work.",
        "default_guidelines": "Treat external systems carefully and surface approval needs early.",
        "default_tools_json": ["integration_work", "env_validation"],
        "default_permissions_json": {"external_access": "approval"},
        "spawn_triggers_json": ["Cross-service or connector work exists"],
        "retirement_triggers_json": ["Integration contract is stable and validated."],
        "risk_profile": "high",
    },
    {
        "name": "test",
        "purpose": "Write and run tests, smoke checks, and validation flows.",
        "default_guidelines": "Never claim tests ran when they did not. Ask for approvals honestly.",
        "default_tools_json": ["test_runner", "smoke_checks"],
        "default_permissions_json": {"run_commands": "approval"},
        "spawn_triggers_json": ["Testing depth is standard or higher"],
        "retirement_triggers_json": ["Validation target is met or blocked with clear evidence."],
        "risk_profile": "medium",
    },
    {
        "name": "reviewer",
        "purpose": "Review changes for coherence, regressions, and missing validation.",
        "default_guidelines": "Prioritize risk discovery over rewriting working code.",
        "default_tools_json": ["code_review", "diff_analysis"],
        "default_permissions_json": {"write_changes": False},
        "spawn_triggers_json": ["Quality focus is high", "Needs-review queue is growing"],
        "retirement_triggers_json": ["Review backlog is cleared."],
        "risk_profile": "low",
    },
    {
        "name": "security",
        "purpose": "Review auth, secrets handling, and risky execution paths.",
        "default_guidelines": "Bias toward least privilege and explicit approval boundaries.",
        "default_tools_json": ["security_review", "config_audit"],
        "default_permissions_json": {"write_changes": False},
        "spawn_triggers_json": ["Auth/security risk is present", "Release quality is required"],
        "retirement_triggers_json": ["Security-critical decisions are documented and reviewed."],
        "risk_profile": "high",
    },
    {
        "name": "docs",
        "purpose": "Write documentation, examples, and handoff material.",
        "default_guidelines": "Keep docs scoped to a named audience and avoid stale claims.",
        "default_tools_json": ["docs_editing", "handoff_notes"],
        "default_permissions_json": {"write_docs": True},
        "spawn_triggers_json": ["Documentation depth is above minimal"],
        "retirement_triggers_json": ["Assigned document set is complete and reviewed."],
        "risk_profile": "low",
    },
    {
        "name": "ops",
        "purpose": "Handle run instructions, environment checks, and deployment packaging.",
        "default_guidelines": "Do not publish or deploy without explicit approval.",
        "default_tools_json": ["runbooks", "runtime_checks"],
        "default_permissions_json": {"deploy": "approval"},
        "spawn_triggers_json": ["Distribution or runtime packaging matters"],
        "retirement_triggers_json": ["Runbook and packaging risks are closed."],
        "risk_profile": "high",
    },
    {
        "name": "research",
        "purpose": "Investigate unknowns, options, and tradeoffs before committing to implementation.",
        "default_guidelines": "Surface decisions, not essay spam.",
        "default_tools_json": ["research", "option_analysis"],
        "default_permissions_json": {"web_access": "approval"},
        "spawn_triggers_json": ["Scope is unclear", "Architecture choices need evidence"],
        "retirement_triggers_json": ["Key unknowns are reduced enough for implementation."],
        "risk_profile": "low",
    },
    {
        "name": "migration",
        "purpose": "Move or upgrade existing systems safely.",
        "default_guidelines": "Protect compatibility and call out irreversible steps.",
        "default_tools_json": ["migration_planning", "compat_checks"],
        "default_permissions_json": {"schema_changes": "approval"},
        "spawn_triggers_json": ["Migration work is in scope"],
        "retirement_triggers_json": ["Migration path is executed or explicitly deferred."],
        "risk_profile": "high",
    },
    {
        "name": "refactor",
        "purpose": "Restructure existing code without changing intended behavior.",
        "default_guidelines": "Prefer small contained path slices with strong review coverage.",
        "default_tools_json": ["refactor_work", "tests"],
        "default_permissions_json": {"write_src": True},
        "spawn_triggers_json": ["Architecture cleanup is part of scope"],
        "retirement_triggers_json": ["Refactor scope is stable and tests are green."],
        "risk_profile": "medium",
    },
    {
        "name": "performance",
        "purpose": "Improve latency, throughput, and heavy-path efficiency.",
        "default_guidelines": "Do not chase micro-optimizations before the product works.",
        "default_tools_json": ["profiling", "benchmarking"],
        "default_permissions_json": {"run_commands": "approval"},
        "spawn_triggers_json": ["Performance constraints are explicit"],
        "retirement_triggers_json": ["Key performance targets are met or documented."],
        "risk_profile": "medium",
    },
    {
        "name": "data",
        "purpose": "Own persistence, schema, and data-flow changes.",
        "default_guidelines": "Protect migrations and surface destructive risk early.",
        "default_tools_json": ["schema_work", "data_validation"],
        "default_permissions_json": {"schema_changes": "approval"},
        "spawn_triggers_json": ["Data/storage work is core to the project"],
        "retirement_triggers_json": ["Data paths are validated and documented."],
        "risk_profile": "high",
    },
    {
        "name": "ui_polish",
        "purpose": "Tighten UX, layout, and visual finish once the slice works.",
        "default_guidelines": "Polish should support usability, not replace substance.",
        "default_tools_json": ["ui_polish", "accessibility_review"],
        "default_permissions_json": {"write_ui": True},
        "spawn_triggers_json": ["The workflow works and polish matters"],
        "retirement_triggers_json": ["Polish pass is complete or explicitly time-boxed."],
        "risk_profile": "low",
    },
    {
        "name": "release_handoff",
        "purpose": "Package run instructions, validation evidence, and handoff output.",
        "default_guidelines": "Never imply release readiness without evidence.",
        "default_tools_json": ["handoff_packaging", "release_notes"],
        "default_permissions_json": {"write_docs": True},
        "spawn_triggers_json": ["Project is nearing validation or handoff"],
        "retirement_triggers_json": ["Handoff package is complete and accepted."],
        "risk_profile": "medium",
    },
]
