from __future__ import annotations

from typing import Any


DASHBOARD_WIDGET_DEFAULTS = [
    "Needs Attention",
    "Active Builds",
    "Recent Handoffs",
    "Runner & Provider Status",
    "Model Capability Overview",
    "Global Agent Reputation",
    "Swarm Budget Overview",
    "Project Health Overview",
    "Imported Projects",
]

PROJECT_WIDGET_DEFAULTS = [
    "Project Playbook",
    "Model Capability Matrix",
    "Agent Reputation",
    "Risk Register",
    "Validation Coverage",
    "Codebase Map",
    "Codebase Understanding",
    "Imported Codebase Safety",
    "Security Policy",
    "Approval Audit Log",
    "AGENTS.md Status",
    "Scan Coverage",
    "Swarm Strategy",
    "Swarm Budget",
    "Agent Contracts",
    "Path Ownership Map",
    "Decision Ledger",
    "Project Health Score",
    "Validation Recipe",
    "Risk Assessment",
    "Manager Assumptions",
    "Handoff Quality",
]


WIDGET_CATALOG: list[dict[str, Any]] = [
    {
        "widget_type": "Needs Attention",
        "title": "Needs Attention",
        "description": "Blocked work, pending approvals, manager questions, and handoffs waiting for review.",
        "scope": "dashboard",
        "default_area": "dashboard_main",
        "default_size": "large",
        "category": "Attention",
        "requires_project": False,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "medium",
    },
    {
        "widget_type": "Active Builds",
        "title": "Active Builds",
        "description": "Shows currently active project work and stages without fake progress numerology.",
        "scope": "dashboard",
        "default_area": "dashboard_main",
        "default_size": "medium",
        "category": "Swarm",
        "requires_project": False,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": None,
    },
    {
        "widget_type": "Recent Handoffs",
        "title": "Recent Handoffs",
        "description": "Recently completed deliverables with evidence status, summaries, and run instructions.",
        "scope": "dashboard",
        "default_area": "dashboard_main",
        "default_size": "medium",
        "category": "Handoff",
        "requires_project": False,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": None,
    },
    {
        "widget_type": "Runner & Provider Status",
        "title": "Runner & Provider Status",
        "description": "Local runtime readiness across CLI, app-server, Codex auth, and Ollama.",
        "scope": "dashboard",
        "default_area": "dashboard_right",
        "default_size": "medium",
        "category": "Diagnostics",
        "requires_project": False,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "low",
    },
    {
        "widget_type": "Imported Projects",
        "title": "Imported Projects",
        "description": "Recently imported local repos, their scan status, safety posture, and codebase size.",
        "scope": "dashboard",
        "default_area": "dashboard_bottom",
        "default_size": "medium",
        "category": "Diagnostics",
        "requires_project": False,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "low",
    },
    {
        "widget_type": "Connected Accounts",
        "title": "Connected Accounts",
        "description": "Connected integrations and provider account state.",
        "scope": "dashboard",
        "default_area": "dashboard_right",
        "default_size": "small",
        "category": "Tools",
        "requires_project": False,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "low",
    },
    {
        "widget_type": "Model Defaults",
        "title": "Model Defaults",
        "description": "Current default manager and worker model policy.",
        "scope": "dashboard",
        "default_area": "dashboard_right",
        "default_size": "small",
        "category": "Models",
        "requires_project": False,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": None,
    },
    {
        "widget_type": "Diagnostics Summary",
        "title": "Diagnostics Summary",
        "description": "Startup mode, runtime status, and recent diagnostic state.",
        "scope": "dashboard",
        "default_area": "dashboard_right",
        "default_size": "small",
        "category": "Diagnostics",
        "requires_project": False,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "medium",
    },
    {
        "widget_type": "Swarm Budget Overview",
        "title": "Swarm Budget Overview",
        "description": "Summarizes active swarm intensity, approval thresholds, and dynamic spawning across projects.",
        "scope": "dashboard",
        "default_area": "dashboard_bottom",
        "default_size": "medium",
        "category": "Swarm",
        "requires_project": False,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "medium",
    },
    {
        "widget_type": "Blocked Agents",
        "title": "Blocked Agents",
        "description": "Agents that are stuck, blocked, or waiting on unresolved conditions.",
        "scope": "dashboard",
        "default_area": "dashboard_bottom",
        "default_size": "medium",
        "category": "Agents",
        "requires_project": False,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "medium",
    },
    {
        "widget_type": "Recent Decisions",
        "title": "Recent Decisions",
        "description": "Recent user, manager, and auto-manager decisions across projects.",
        "scope": "dashboard",
        "default_area": "dashboard_bottom",
        "default_size": "medium",
        "category": "Change Management",
        "requires_project": False,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": None,
    },
    {
        "widget_type": "Project Health Overview",
        "title": "Project Health Overview",
        "description": "Health state and top risks across active projects.",
        "scope": "dashboard",
        "default_area": "dashboard_bottom",
        "default_size": "large",
        "category": "Quality",
        "requires_project": False,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "medium",
    },
    {
        "widget_type": "Recent Change Requests",
        "title": "Recent Change Requests",
        "description": "Recent project-level change requests and their triage state.",
        "scope": "dashboard",
        "default_area": "dashboard_bottom",
        "default_size": "medium",
        "category": "Change Management",
        "requires_project": False,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": None,
    },
    {
        "widget_type": "Active Conflicts",
        "title": "Active Conflicts",
        "description": "Open path collisions, dependency conflicts, and merge pressure across projects.",
        "scope": "dashboard",
        "default_area": "dashboard_bottom",
        "default_size": "medium",
        "category": "Safety",
        "requires_project": False,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "high",
    },
    {
        "widget_type": "Recovery Needed",
        "title": "Recovery Needed",
        "description": "Projects with active recovery proposals, stuck agents, or blocked execution paths.",
        "scope": "dashboard",
        "default_area": "dashboard_bottom",
        "default_size": "medium",
        "category": "Attention",
        "requires_project": False,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "medium",
    },
    {
        "widget_type": "Model Capability Overview",
        "title": "Model Capability Overview",
        "description": "Recorded benchmark coverage across models, categories, and runner modes.",
        "scope": "dashboard",
        "default_area": "dashboard_right",
        "default_size": "medium",
        "category": "Models",
        "requires_project": False,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": None,
    },
    {
        "widget_type": "Global Agent Reputation",
        "title": "Global Agent Reputation",
        "description": "Best and worst-performing archetypes/models across projects based on actual history.",
        "scope": "dashboard",
        "default_area": "dashboard_bottom",
        "default_size": "medium",
        "category": "Agents",
        "requires_project": False,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "medium",
    },
    {
        "widget_type": "Common Risks",
        "title": "Common Risks",
        "description": "Recently active cross-project planning and execution risks.",
        "scope": "dashboard",
        "default_area": "dashboard_bottom",
        "default_size": "medium",
        "category": "Safety",
        "requires_project": False,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "high",
    },
    {
        "widget_type": "Recent Scope Changes",
        "title": "Recent Scope Changes",
        "description": "Open scope creep signals that the Manager should not pretend are harmless.",
        "scope": "dashboard",
        "default_area": "dashboard_bottom",
        "default_size": "medium",
        "category": "Change Management",
        "requires_project": False,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "medium",
    },
    {
        "widget_type": "Preference Summary",
        "title": "Preference Summary",
        "description": "Global workflow preferences that are currently shaping Mission Control behavior.",
        "scope": "dashboard",
        "default_area": "dashboard_right",
        "default_size": "small",
        "category": "Change Management",
        "requires_project": False,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": None,
    },
    {
        "widget_type": "Codebase Map",
        "title": "Codebase Map",
        "description": "Detected stack, commands, important folders, docs, and risk flags for an imported repo.",
        "scope": "project",
        "default_area": "project_overview",
        "default_size": "large",
        "category": "Diagnostics",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "low",
    },
    {
        "widget_type": "Codebase Understanding",
        "title": "Codebase Understanding",
        "description": "High-signal summary of what the imported repo appears to be and how it is structured.",
        "scope": "project",
        "default_area": "project_overview",
        "default_size": "large",
        "category": "Docs",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "low",
    },
    {
        "widget_type": "Imported Codebase Safety",
        "title": "Imported Codebase Safety",
        "description": "Read/write mode, snapshot recommendation, and approval gates for imported codebases.",
        "scope": "project",
        "default_area": "project_right_sidebar",
        "default_size": "medium",
        "category": "Safety",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "high",
    },
    {
        "widget_type": "Security Policy",
        "title": "Security Policy",
        "description": "Project-scoped approval, network, write, deployment, and destructive-action posture.",
        "scope": "project",
        "default_area": "project_right_sidebar",
        "default_size": "medium",
        "category": "Safety",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "high",
    },
    {
        "widget_type": "Approval Audit Log",
        "title": "Approval Audit Log",
        "description": "Recent approval decisions, policy blocks, and auto-approval events with redacted detail.",
        "scope": "project",
        "default_area": "project_bottom",
        "default_size": "large",
        "category": "Safety",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "medium",
    },
    {
        "widget_type": "Risk Assessment",
        "title": "Risk Assessment",
        "description": "Latest deterministic risk classifications for commands, tools, plugins, and external actions.",
        "scope": "project",
        "default_area": "project_bottom",
        "default_size": "medium",
        "category": "Safety",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "medium",
    },
    {
        "widget_type": "AGENTS.md Status",
        "title": "AGENTS.md Status",
        "description": "Presence, summary, and recommended action for AGENTS.md in the imported repo.",
        "scope": "project",
        "default_area": "project_right_sidebar",
        "default_size": "medium",
        "category": "Docs",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "low",
    },
    {
        "widget_type": "Scan Coverage",
        "title": "Scan Coverage",
        "description": "Scan depth, codebase size, indexed areas, unindexed areas, and targeted scan posture.",
        "scope": "project",
        "default_area": "project_overview",
        "default_size": "medium",
        "category": "Diagnostics",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "low",
    },
    {
        "widget_type": "Swarm Budget",
        "title": "Swarm Budget",
        "description": "Agent count, intensity, approval threshold, and dynamic spawning controls.",
        "scope": "project",
        "default_area": "project_right_sidebar",
        "default_size": "medium",
        "category": "Swarm",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "medium",
    },
    {
        "widget_type": "Conflict Resolver",
        "title": "Conflict Resolver",
        "description": "Active conflicts, affected paths, involved agents, and the recommended mediation strategy.",
        "scope": "project",
        "default_area": "project_right_sidebar",
        "default_size": "medium",
        "category": "Safety",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "high",
    },
    {
        "widget_type": "Evidence Handoff",
        "title": "Evidence Handoff",
        "description": "Handoff readiness, supporting evidence, missing proof, and confidence level.",
        "scope": "project",
        "default_area": "project_right_sidebar",
        "default_size": "medium",
        "category": "Handoff",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "medium",
    },
    {
        "widget_type": "Runbook",
        "title": "Runbook",
        "description": "Operational instructions for build, test, debug, reset, logs, and deployment posture.",
        "scope": "project",
        "default_area": "project_right_sidebar",
        "default_size": "medium",
        "category": "Docs",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": None,
    },
    {
        "widget_type": "Agent Black Box",
        "title": "Agent Black Box",
        "description": "Recent redacted execution traces, files changed, approvals requested, and manager follow-up decisions.",
        "scope": "project",
        "default_area": "project_bottom",
        "default_size": "medium",
        "category": "Diagnostics",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "medium",
    },
    {
        "widget_type": "Snapshots",
        "title": "Snapshots",
        "description": "Recent restore points and safe restore plans for risky project changes.",
        "scope": "project",
        "default_area": "project_right_sidebar",
        "default_size": "medium",
        "category": "Safety",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "high",
    },
    {
        "widget_type": "Agent Load Balancer",
        "title": "Agent Load Balancer",
        "description": "Idle versus overloaded agents with suggested reassignments that still respect contracts and path ownership.",
        "scope": "project",
        "default_area": "project_right_sidebar",
        "default_size": "medium",
        "category": "Agents",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "medium",
    },
    {
        "widget_type": "Agent Contracts",
        "title": "Agent Contracts",
        "description": "Mission boundaries, path ownership, tools, outputs, and stop conditions for active agents.",
        "scope": "project",
        "default_area": "project_right_sidebar",
        "default_size": "large",
        "category": "Agents",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "medium",
    },
    {
        "widget_type": "Path Ownership Map",
        "title": "Path Ownership Map",
        "description": "Current path locks, owners, waiting tasks, and conflict warnings.",
        "scope": "project",
        "default_area": "project_right_sidebar",
        "default_size": "medium",
        "category": "Safety",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "high",
    },
    {
        "widget_type": "Decision Ledger",
        "title": "Decision Ledger",
        "description": "Recent decisions, assumptions, approval history, and rejected options.",
        "scope": "project",
        "default_area": "project_right_sidebar",
        "default_size": "large",
        "category": "Change Management",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": None,
    },
    {
        "widget_type": "Confidence Tracker",
        "title": "Confidence Tracker",
        "description": "Confidence by category with unknowns and weakest planning areas.",
        "scope": "project",
        "default_area": "project_overview",
        "default_size": "medium",
        "category": "Attention",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": None,
    },
    {
        "widget_type": "Model Capability Matrix",
        "title": "Model Capability Matrix",
        "description": "Capability benchmark matrix used for model assignment hints and honest unknown states.",
        "scope": "project",
        "default_area": "project_overview",
        "default_size": "large",
        "category": "Models",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": None,
    },
    {
        "widget_type": "Agent Reputation",
        "title": "Agent Reputation",
        "description": "Project-specific agent/model performance history, strengths, and weak spots.",
        "scope": "project",
        "default_area": "project_overview",
        "default_size": "medium",
        "category": "Agents",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "medium",
    },
    {
        "widget_type": "Project Playbook",
        "title": "Project Playbook",
        "description": "Suggested or applied playbook, why it fits, and the baseline risk/validation posture.",
        "scope": "project",
        "default_area": "project_right_sidebar",
        "default_size": "medium",
        "category": "Change Management",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "low",
    },
    {
        "widget_type": "Context Packs",
        "title": "Context Packs",
        "description": "Recent agent context packs with scope breadth warnings and inclusion counts.",
        "scope": "project",
        "default_area": "project_bottom",
        "default_size": "medium",
        "category": "Agents",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "medium",
    },
    {
        "widget_type": "Risk Register",
        "title": "Risk Register",
        "description": "Top project risks, mitigation plans, owners, and current status.",
        "scope": "project",
        "default_area": "project_right_sidebar",
        "default_size": "large",
        "category": "Safety",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "high",
    },
    {
        "widget_type": "Scope Creep",
        "title": "Scope Creep",
        "description": "Open scope change signals and recommended actions before the project sprawls into nonsense.",
        "scope": "project",
        "default_area": "project_overview",
        "default_size": "medium",
        "category": "Change Management",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "medium",
    },
    {
        "widget_type": "Agent Launch Simulation",
        "title": "Agent Launch Simulation",
        "description": "Pre-launch swarm safety check for overlaps, waits, approvals, and bottlenecks.",
        "scope": "project",
        "default_area": "project_right_sidebar",
        "default_size": "medium",
        "category": "Safety",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "high",
    },
    {
        "widget_type": "Validation Coverage",
        "title": "Validation Coverage",
        "description": "What is validated, what is only planned, and what is still assumed.",
        "scope": "project",
        "default_area": "project_overview",
        "default_size": "medium",
        "category": "Quality",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "medium",
    },
    {
        "widget_type": "Preference Memory",
        "title": "Preference Memory",
        "description": "Active workflow preferences shaping this project, with source and editability.",
        "scope": "project",
        "default_area": "project_right_sidebar",
        "default_size": "small",
        "category": "Change Management",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": None,
    },
    {
        "widget_type": "Swarm Strategy",
        "title": "Swarm Strategy",
        "description": "Current swarm mode, bottlenecks, risks, and scaling posture.",
        "scope": "project",
        "default_area": "project_right_sidebar",
        "default_size": "large",
        "category": "Swarm",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "medium",
    },
    {
        "widget_type": "What Changed Timeline",
        "title": "What Changed Timeline",
        "description": "High-signal recent changes synthesized from events and manager updates.",
        "scope": "project",
        "default_area": "project_bottom",
        "default_size": "medium",
        "category": "Change Management",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": None,
    },
    {
        "widget_type": "Agent Report Inbox",
        "title": "Agent Report Inbox",
        "description": "Recent worker reports and summaries that need manager attention.",
        "scope": "project",
        "default_area": "project_bottom",
        "default_size": "medium",
        "category": "Agents",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": None,
    },
    {
        "widget_type": "Failure Recovery",
        "title": "Failure Recovery",
        "description": "Suggested recovery options for current failures or blocked work.",
        "scope": "project",
        "default_area": "project_right_sidebar",
        "default_size": "medium",
        "category": "Attention",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "medium",
    },
    {
        "widget_type": "Agent Stuck Detection",
        "title": "Agent Stuck Detection",
        "description": "Flags no-progress agents and repeated failure patterns.",
        "scope": "project",
        "default_area": "project_right_sidebar",
        "default_size": "medium",
        "category": "Agents",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "medium",
    },
    {
        "widget_type": "Parallelism Safety Meter",
        "title": "Parallelism Safety Meter",
        "description": "Summarizes conflict pressure between swarm parallelism and path safety.",
        "scope": "project",
        "default_area": "project_overview",
        "default_size": "small",
        "category": "Safety",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "high",
    },
    {
        "widget_type": "Merge / Review Gates",
        "title": "Merge / Review Gates",
        "description": "Required and optional review/test/security/docs/handoff gates.",
        "scope": "project",
        "default_area": "project_right_sidebar",
        "default_size": "medium",
        "category": "Quality",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "medium",
    },
    {
        "widget_type": "Project Health Score",
        "title": "Project Health Score",
        "description": "Current health, top risks, readiness, and next recommended action.",
        "scope": "project",
        "default_area": "project_right_sidebar",
        "default_size": "medium",
        "category": "Quality",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "medium",
    },
    {
        "widget_type": "Human Attention Queue",
        "title": "Human Attention Queue",
        "description": "Project-scoped summary of approvals, questions, and manual attention items.",
        "scope": "project",
        "default_area": "project_overview",
        "default_size": "small",
        "category": "Attention",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": None,
    },
    {
        "widget_type": "Model Assignment Policy",
        "title": "Model Assignment Policy",
        "description": "Current model policy and role-to-model mapping with fallback warnings.",
        "scope": "project",
        "default_area": "project_right_sidebar",
        "default_size": "medium",
        "category": "Models",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": None,
    },
    {
        "widget_type": "Tool Routing Policy",
        "title": "Tool Routing Policy",
        "description": "Allowed tools, approval-required tools, and blocked tools by agent archetype.",
        "scope": "project",
        "default_area": "project_right_sidebar",
        "default_size": "large",
        "category": "Tools",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "medium",
    },
    {
        "widget_type": "Sandbox Profiles",
        "title": "Sandbox Profiles",
        "description": "Current sandbox profile, network posture, file write policy, and approval policy.",
        "scope": "project",
        "default_area": "project_right_sidebar",
        "default_size": "medium",
        "category": "Safety",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "high",
    },
    {
        "widget_type": "Manager Assumptions",
        "title": "Manager Assumptions",
        "description": "Active manager assumptions and their confidence and impact.",
        "scope": "project",
        "default_area": "project_right_sidebar",
        "default_size": "medium",
        "category": "Attention",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": None,
    },
    {
        "widget_type": "Repo Intelligence",
        "title": "Repo Intelligence",
        "description": "Lightweight codebase scan showing languages, frameworks, commands, and risky areas.",
        "scope": "project",
        "default_area": "project_overview",
        "default_size": "large",
        "category": "Diagnostics",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "low",
    },
    {
        "widget_type": "Validation Recipe",
        "title": "Validation Recipe",
        "description": "Current validation sequence, required approvals, and recent result state.",
        "scope": "project",
        "default_area": "project_right_sidebar",
        "default_size": "medium",
        "category": "Quality",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "medium",
    },
    {
        "widget_type": "Handoff Quality",
        "title": "Handoff Quality",
        "description": "Current handoff quality level, included sections, and readiness state.",
        "scope": "project",
        "default_area": "project_right_sidebar",
        "default_size": "medium",
        "category": "Handoff",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": None,
    },
    {
        "widget_type": "Change Request Mode",
        "title": "Change Request Mode",
        "description": "Tracked change requests, classifications, and manager triage status.",
        "scope": "project",
        "default_area": "project_right_sidebar",
        "default_size": "medium",
        "category": "Change Management",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": None,
    },
    {
        "widget_type": "Live Project Map",
        "title": "Live Project Map",
        "description": "Experimental live graph of agent/task/review relationships.",
        "scope": "project",
        "default_area": "project_custom",
        "default_size": "full",
        "category": "Swarm",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": True,
        "risk_level": None,
    },
    {
        "widget_type": "Handoff Progress",
        "title": "Handoff Progress",
        "description": "Checklist-based handoff completion and readiness signal.",
        "scope": "project",
        "default_area": "project_overview",
        "default_size": "small",
        "category": "Handoff",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": None,
    },
]


WIDGET_CATALOG_BY_TYPE = {item["widget_type"]: item for item in WIDGET_CATALOG}
DASHBOARD_WIDGET_TYPES = [item["widget_type"] for item in WIDGET_CATALOG if item["scope"] == "dashboard"]
PROJECT_WIDGET_TYPES = [item["widget_type"] for item in WIDGET_CATALOG if item["scope"] == "project"]
