from __future__ import annotations

from typing import Any


DASHBOARD_WIDGET_DEFAULTS = [
    "Needs Attention",
    "Active Builds",
    "Recent Handoffs",
    "Runner & Provider Status",
    "Swarm Budget Overview",
    "Project Health Overview",
]

PROJECT_WIDGET_DEFAULTS = [
    "Swarm Strategy",
    "Swarm Budget",
    "Agent Contracts",
    "Path Ownership Map",
    "Decision Ledger",
    "Project Health Score",
    "Validation Recipe",
    "Manager Assumptions",
    "Handoff Quality",
]


WIDGET_CATALOG: list[dict[str, Any]] = [
    {
        "widget_type": "Needs Attention",
        "title": "Needs Attention",
        "description": "Blocked work, pending approvals, manager questions, and handoffs waiting for review.",
        "scope": "dashboard",
        "default_area": "dashboard_main",
        "default_size": "large",
        "category": "Attention",
        "requires_project": False,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "medium",
    },
    {
        "widget_type": "Active Builds",
        "title": "Active Builds",
        "description": "Shows currently active project work and stages without fake progress numerology.",
        "scope": "dashboard",
        "default_area": "dashboard_main",
        "default_size": "medium",
        "category": "Swarm",
        "requires_project": False,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": None,
    },
    {
        "widget_type": "Recent Handoffs",
        "title": "Recent Handoffs",
        "description": "Recently completed deliverables with summaries and run instructions.",
        "scope": "dashboard",
        "default_area": "dashboard_main",
        "default_size": "medium",
        "category": "Handoff",
        "requires_project": False,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": None,
    },
    {
        "widget_type": "Runner & Provider Status",
        "title": "Runner & Provider Status",
        "description": "Local runtime readiness across CLI, app-server, Codex auth, and Ollama.",
        "scope": "dashboard",
        "default_area": "dashboard_right",
        "default_size": "medium",
        "category": "Diagnostics",
        "requires_project": False,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "low",
    },
    {
        "widget_type": "Connected Accounts",
        "title": "Connected Accounts",
        "description": "Connected integrations and provider account state.",
        "scope": "dashboard",
        "default_area": "dashboard_right",
        "default_size": "small",
        "category": "Tools",
        "requires_project": False,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "low",
    },
    {
        "widget_type": "Model Defaults",
        "title": "Model Defaults",
        "description": "Current default manager and worker model policy.",
        "scope": "dashboard",
        "default_area": "dashboard_right",
        "default_size": "small",
        "category": "Models",
        "requires_project": False,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": None,
    },
    {
        "widget_type": "Diagnostics Summary",
        "title": "Diagnostics Summary",
        "description": "Startup mode, runtime status, and recent diagnostic state.",
        "scope": "dashboard",
        "default_area": "dashboard_right",
        "default_size": "small",
        "category": "Diagnostics",
        "requires_project": False,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "medium",
    },
    {
        "widget_type": "Swarm Budget Overview",
        "title": "Swarm Budget Overview",
        "description": "Summarizes active swarm intensity, approval thresholds, and dynamic spawning across projects.",
        "scope": "dashboard",
        "default_area": "dashboard_bottom",
        "default_size": "medium",
        "category": "Swarm",
        "requires_project": False,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "medium",
    },
    {
        "widget_type": "Blocked Agents",
        "title": "Blocked Agents",
        "description": "Agents that are stuck, blocked, or waiting on unresolved conditions.",
        "scope": "dashboard",
        "default_area": "dashboard_bottom",
        "default_size": "medium",
        "category": "Agents",
        "requires_project": False,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "medium",
    },
    {
        "widget_type": "Recent Decisions",
        "title": "Recent Decisions",
        "description": "Recent user, manager, and auto-manager decisions across projects.",
        "scope": "dashboard",
        "default_area": "dashboard_bottom",
        "default_size": "medium",
        "category": "Change Management",
        "requires_project": False,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": None,
    },
    {
        "widget_type": "Project Health Overview",
        "title": "Project Health Overview",
        "description": "Health state and top risks across active projects.",
        "scope": "dashboard",
        "default_area": "dashboard_bottom",
        "default_size": "large",
        "category": "Quality",
        "requires_project": False,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "medium",
    },
    {
        "widget_type": "Recent Change Requests",
        "title": "Recent Change Requests",
        "description": "Recent project-level change requests and their triage state.",
        "scope": "dashboard",
        "default_area": "dashboard_bottom",
        "default_size": "medium",
        "category": "Change Management",
        "requires_project": False,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": None,
    },
    {
        "widget_type": "Swarm Budget",
        "title": "Swarm Budget",
        "description": "Agent count, intensity, approval threshold, and dynamic spawning controls.",
        "scope": "project",
        "default_area": "project_right_sidebar",
        "default_size": "medium",
        "category": "Swarm",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "medium",
    },
    {
        "widget_type": "Agent Contracts",
        "title": "Agent Contracts",
        "description": "Mission boundaries, path ownership, tools, outputs, and stop conditions for active agents.",
        "scope": "project",
        "default_area": "project_right_sidebar",
        "default_size": "large",
        "category": "Agents",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "medium",
    },
    {
        "widget_type": "Path Ownership Map",
        "title": "Path Ownership Map",
        "description": "Current path locks, owners, waiting tasks, and conflict warnings.",
        "scope": "project",
        "default_area": "project_right_sidebar",
        "default_size": "medium",
        "category": "Safety",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "high",
    },
    {
        "widget_type": "Decision Ledger",
        "title": "Decision Ledger",
        "description": "Recent decisions, assumptions, approval history, and rejected options.",
        "scope": "project",
        "default_area": "project_right_sidebar",
        "default_size": "large",
        "category": "Change Management",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": None,
    },
    {
        "widget_type": "Confidence Tracker",
        "title": "Confidence Tracker",
        "description": "Confidence by category with unknowns and weakest planning areas.",
        "scope": "project",
        "default_area": "project_overview",
        "default_size": "medium",
        "category": "Attention",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": None,
    },
    {
        "widget_type": "Swarm Strategy",
        "title": "Swarm Strategy",
        "description": "Current swarm mode, bottlenecks, risks, and scaling posture.",
        "scope": "project",
        "default_area": "project_right_sidebar",
        "default_size": "large",
        "category": "Swarm",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "medium",
    },
    {
        "widget_type": "What Changed Timeline",
        "title": "What Changed Timeline",
        "description": "High-signal recent changes synthesized from events and manager updates.",
        "scope": "project",
        "default_area": "project_bottom",
        "default_size": "medium",
        "category": "Change Management",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": None,
    },
    {
        "widget_type": "Agent Report Inbox",
        "title": "Agent Report Inbox",
        "description": "Recent worker reports and summaries that need manager attention.",
        "scope": "project",
        "default_area": "project_bottom",
        "default_size": "medium",
        "category": "Agents",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": None,
    },
    {
        "widget_type": "Failure Recovery",
        "title": "Failure Recovery",
        "description": "Suggested recovery options for current failures or blocked work.",
        "scope": "project",
        "default_area": "project_right_sidebar",
        "default_size": "medium",
        "category": "Attention",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "medium",
    },
    {
        "widget_type": "Agent Stuck Detection",
        "title": "Agent Stuck Detection",
        "description": "Flags no-progress agents and repeated failure patterns.",
        "scope": "project",
        "default_area": "project_right_sidebar",
        "default_size": "medium",
        "category": "Agents",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "medium",
    },
    {
        "widget_type": "Parallelism Safety Meter",
        "title": "Parallelism Safety Meter",
        "description": "Summarizes conflict pressure between swarm parallelism and path safety.",
        "scope": "project",
        "default_area": "project_overview",
        "default_size": "small",
        "category": "Safety",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "high",
    },
    {
        "widget_type": "Merge / Review Gates",
        "title": "Merge / Review Gates",
        "description": "Required and optional review/test/security/docs/handoff gates.",
        "scope": "project",
        "default_area": "project_right_sidebar",
        "default_size": "medium",
        "category": "Quality",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "medium",
    },
    {
        "widget_type": "Project Health Score",
        "title": "Project Health Score",
        "description": "Current health, top risks, readiness, and next recommended action.",
        "scope": "project",
        "default_area": "project_right_sidebar",
        "default_size": "medium",
        "category": "Quality",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "medium",
    },
    {
        "widget_type": "Human Attention Queue",
        "title": "Human Attention Queue",
        "description": "Project-scoped summary of approvals, questions, and manual attention items.",
        "scope": "project",
        "default_area": "project_overview",
        "default_size": "small",
        "category": "Attention",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": None,
    },
    {
        "widget_type": "Model Assignment Policy",
        "title": "Model Assignment Policy",
        "description": "Current model policy and role-to-model mapping with fallback warnings.",
        "scope": "project",
        "default_area": "project_right_sidebar",
        "default_size": "medium",
        "category": "Models",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": None,
    },
    {
        "widget_type": "Tool Routing Policy",
        "title": "Tool Routing Policy",
        "description": "Allowed tools, approval-required tools, and blocked tools by agent archetype.",
        "scope": "project",
        "default_area": "project_right_sidebar",
        "default_size": "large",
        "category": "Tools",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "medium",
    },
    {
        "widget_type": "Sandbox Profiles",
        "title": "Sandbox Profiles",
        "description": "Current sandbox profile, network posture, file write policy, and approval policy.",
        "scope": "project",
        "default_area": "project_right_sidebar",
        "default_size": "medium",
        "category": "Safety",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "high",
    },
    {
        "widget_type": "Manager Assumptions",
        "title": "Manager Assumptions",
        "description": "Active manager assumptions and their confidence and impact.",
        "scope": "project",
        "default_area": "project_right_sidebar",
        "default_size": "medium",
        "category": "Attention",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": None,
    },
    {
        "widget_type": "Repo Intelligence",
        "title": "Repo Intelligence",
        "description": "Lightweight codebase scan showing languages, frameworks, commands, and risky areas.",
        "scope": "project",
        "default_area": "project_overview",
        "default_size": "large",
        "category": "Diagnostics",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "low",
    },
    {
        "widget_type": "Validation Recipe",
        "title": "Validation Recipe",
        "description": "Current validation sequence, required approvals, and recent result state.",
        "scope": "project",
        "default_area": "project_right_sidebar",
        "default_size": "medium",
        "category": "Quality",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": "medium",
    },
    {
        "widget_type": "Handoff Quality",
        "title": "Handoff Quality",
        "description": "Current handoff quality level, included sections, and readiness state.",
        "scope": "project",
        "default_area": "project_right_sidebar",
        "default_size": "medium",
        "category": "Handoff",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": None,
    },
    {
        "widget_type": "Change Request Mode",
        "title": "Change Request Mode",
        "description": "Tracked change requests, classifications, and manager triage status.",
        "scope": "project",
        "default_area": "project_right_sidebar",
        "default_size": "medium",
        "category": "Change Management",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": None,
    },
    {
        "widget_type": "Live Project Map",
        "title": "Live Project Map",
        "description": "Experimental live graph of agent/task/review relationships.",
        "scope": "project",
        "default_area": "project_custom",
        "default_size": "full",
        "category": "Swarm",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": True,
        "risk_level": None,
    },
    {
        "widget_type": "Handoff Progress",
        "title": "Handoff Progress",
        "description": "Checklist-based handoff completion and readiness signal.",
        "scope": "project",
        "default_area": "project_overview",
        "default_size": "small",
        "category": "Handoff",
        "requires_project": True,
        "requires_tool": None,
        "coming_soon": False,
        "risk_level": None,
    },
]


WIDGET_CATALOG_BY_TYPE = {item["widget_type"]: item for item in WIDGET_CATALOG}
DASHBOARD_WIDGET_TYPES = [item["widget_type"] for item in WIDGET_CATALOG if item["scope"] == "dashboard"]
PROJECT_WIDGET_TYPES = [item["widget_type"] for item in WIDGET_CATALOG if item["scope"] == "project"]
