from __future__ import annotations


BREAKPOINT_DESCRIPTIONS: dict[str, str] = {
    "bootstrap.start": "Bootstrap flow entrypoint.",
    "bootstrap.environment_probe": "Environment probe for local tools and runtime paths.",
    "bootstrap.dependency_probe": "Dependency probe for required local executables.",
    "bootstrap.runner_probe": "Runner detection and capability probe.",
    "bootstrap.runner_autowire": "Runner autowire and default selection.",
    "bootstrap.headless_config_write": "Background-running config generation and write step.",
    "bootstrap.install_report": "Install report assembly.",
    "bootstrap.health_check": "Background-running health check generation.",
    "daemon.start": "Daemon startup.",
    "daemon.health_check": "Daemon health verification.",
    "daemon.stop": "Daemon shutdown.",
    "daemon.pid_check": "PID file or daemon metadata validation.",
    "daemon.port_bind": "Daemon port binding.",
    "mcp.start": "MCP bridge startup.",
    "mcp.handshake": "MCP handshake and reachability check.",
    "mcp.tool_call": "MCP tool execution.",
    "mcp.resource_read": "MCP resource read.",
    "mcp.prompt_render": "MCP prompt rendering.",
    "plugin.skill_discovery": "Skill discovery and registration.",
    "plugin.package_validate": "Plugin package validation.",
    "workspace.attach": "Workspace attach flow.",
    "workspace.detect_existing": "Existing codebase detection.",
    "workspace.import_existing_codebase": "Existing codebase import flow.",
    "workspace.read_only_scan": "Read-only scan flow.",
    "workspace.write_permission_request": "Write permission request generation.",
    "orchestration.create": "Orchestration session creation.",
    "orchestration.plan": "Orchestration planning.",
    "orchestration.waiting_for_user": "Orchestration waiting for user action.",
    "orchestration.resume_after_decision": "Resume after a decision is answered.",
    "orchestration.complete": "Orchestration completion.",
    "orchestration.fail": "Orchestration failure handling.",
    "manager.analyze_request": "Manager request analysis.",
    "manager.generate_plan": "Manager plan generation.",
    "manager.create_swarm_plan": "Manager swarm plan creation.",
    "manager.create_pending_decision": "Manager pending decision creation.",
    "manager.consume_agent_report": "Manager handling agent output.",
    "manager.generate_handoff": "Manager handoff generation.",
    "runner.registry_load": "Runner registry load.",
    "runner.select": "Runner selection.",
    "runner.start": "Runner start.",
    "runner.stream_events": "Runner event streaming.",
    "runner.complete": "Runner completion.",
    "runner.fail": "Runner failure.",
    "codex_cli.detect": "Codex CLI detection.",
    "codex_cli.login_status": "Codex CLI login state check.",
    "codex_cli.exec": "Codex CLI execution.",
    "ollama.detect": "Ollama CLI detection.",
    "ollama.server_check": "Ollama server reachability check.",
    "ollama.model_list": "Ollama model listing.",
    "claude_cli.detect": "Claude CLI detection.",
    "claude_cli.auth_status": "Claude CLI auth state check.",
    "api_provider.detect": "API-backed runner detection.",
    "api_provider.auth_check": "API-backed runner auth check.",
    "decision.create": "Pending decision creation.",
    "decision.render": "Pending decision rendering.",
    "decision.answer": "Pending decision answer handling.",
    "decision.validate_option": "Pending decision option validation.",
    "decision.apply": "Pending decision application.",
    "decision.expire": "Pending decision expiration.",
    "bridge.format_status": "Status summary formatting.",
    "bridge.format_approval": "Approval summary formatting.",
    "bridge.format_question": "Manager question formatting.",
    "bridge.format_handoff": "Handoff summary formatting.",
    "bridge.redact_output": "Bridge-safe redaction.",
    "handoff.collect_evidence": "Evidence collection for handoff.",
    "handoff.generate": "Handoff generation.",
    "handoff.validate_claims": "Validation of handoff claims.",
    "handoff.render_chat_summary": "Chat summary rendering for handoff.",
    "diagnostics.run": "Diagnostic run entrypoint.",
    "diagnostics.collect_logs": "Diagnostic log collection.",
    "diagnostics.redact": "Diagnostic redaction.",
    "diagnostics.write_report": "Diagnostic report write step.",
    "subagent_burst.plan": "Subagent burst planning.",
    "subagent_burst.approve": "Subagent burst approval decision.",
    "subagent_burst.spawn_prompt": "Subagent spawn prompt generation.",
    "subagent_burst.ingest_result": "Subagent result ingestion.",
    "subagent_burst.summarize": "Subagent burst summary generation.",
}


def is_known_breakpoint(breakpoint: str) -> bool:
    return breakpoint in BREAKPOINT_DESCRIPTIONS
