from __future__ import annotations

from dataclasses import dataclass

from errors.codes import docs_anchor_for_code
from errors.families import is_known_family
from errors.severity import normalize_severity


@dataclass(frozen=True)
class ErrorDefinition:
    code: str
    family: str
    title: str
    default_detail: str
    severity: str
    default_breakpoint: str
    retryable: bool
    user_action_required: bool
    recommended_fix: str
    http_status: int
    docs_anchor: str


def _entry(
    code: str,
    *,
    family: str,
    title: str,
    detail: str,
    severity: str,
    breakpoint: str,
    retryable: bool,
    user_action_required: bool,
    recommended_fix: str,
    http_status: int,
) -> ErrorDefinition:
    if not is_known_family(family):
        raise ValueError(f"Unknown error family: {family}")
    return ErrorDefinition(
        code=code,
        family=family,
        title=title,
        default_detail=detail,
        severity=normalize_severity(severity),
        default_breakpoint=breakpoint,
        retryable=retryable,
        user_action_required=user_action_required,
        recommended_fix=recommended_fix,
        http_status=http_status,
        docs_anchor=docs_anchor_for_code(code),
    )


_DEFINITIONS = [
    _entry("MC-BOOT-RUNTIME-PATH-001", family="MC-BOOT", title="Runtime path unavailable", detail="Mission Control could not prepare the required runtime paths.", severity="fatal", breakpoint="bootstrap.start", retryable=True, user_action_required=True, recommended_fix="Verify that the runtime directory exists and is writable, then rerun startup.", http_status=500),
    _entry("MC-BOOT-DEPENDENCY-MISSING-001", family="MC-BOOT", title="Required dependency missing", detail="A required local dependency was not found during bootstrap.", severity="error", breakpoint="bootstrap.dependency_probe", retryable=True, user_action_required=True, recommended_fix="Install the missing local dependency or expose it on PATH, then rerun bootstrap.", http_status=503),
    _entry("MC-BOOT-INSTALL-REPORT-FAILED-001", family="MC-BOOT", title="Install report failed", detail="Mission Control could not build the install report.", severity="error", breakpoint="bootstrap.install_report", retryable=True, user_action_required=False, recommended_fix="Rerun the install flow after verifying runner probes and plugin health.", http_status=500),
    _entry("MC-CONFIG-HEADLESS-MISSING-001", family="MC-CONFIG", title="Background-running config missing", detail="The background-running configuration file could not be found.", severity="warning", breakpoint="bootstrap.headless_config_write", retryable=True, user_action_required=True, recommended_fix="Generate the background-running configuration again before continuing.", http_status=404),
    _entry("MC-CONFIG-HEADLESS-INVALID-001", family="MC-CONFIG", title="Background-running config invalid", detail="The background-running configuration is present but invalid.", severity="error", breakpoint="bootstrap.headless_config_write", retryable=True, user_action_required=True, recommended_fix="Repair or regenerate the background-running configuration.", http_status=400),
    _entry("MC-CONFIG-WRITE-FAILED-001", family="MC-CONFIG", title="Config write failed", detail="Mission Control could not write the background-running configuration.", severity="error", breakpoint="bootstrap.headless_config_write", retryable=True, user_action_required=True, recommended_fix="Fix filesystem permissions and rerun the configuration step.", http_status=500),
    _entry("MC-DAEMON-NOT-RUNNING-001", family="MC-DAEMON", title="Daemon not running", detail="Mission Control daemon is not currently running.", severity="error", breakpoint="daemon.health_check", retryable=True, user_action_required=True, recommended_fix="Start the Mission Control daemon locally and verify the health endpoint responds.", http_status=503),
    _entry("MC-DAEMON-PORT-IN-USE-001", family="MC-DAEMON", title="Daemon port already in use", detail="Mission Control could not bind the requested daemon port.", severity="error", breakpoint="daemon.port_bind", retryable=True, user_action_required=True, recommended_fix="Free the port or configure a different local port, then restart the daemon.", http_status=409),
    _entry("MC-DAEMON-HEALTH-FAILED-001", family="MC-DAEMON", title="Daemon health check failed", detail="Mission Control daemon did not pass its local health check.", severity="error", breakpoint="daemon.health_check", retryable=True, user_action_required=True, recommended_fix="Inspect the daemon startup state and rerun the local health check.", http_status=503),
    _entry("MC-DAEMON-PID-STALE-001", family="MC-DAEMON", title="Daemon PID metadata stale", detail="Mission Control found stale daemon metadata.", severity="warning", breakpoint="daemon.pid_check", retryable=True, user_action_required=False, recommended_fix="Clear stale daemon metadata and restart the daemon if necessary.", http_status=409),
    _entry("MC-MCP-BRIDGE-MISSING-001", family="MC-MCP", title="MCP bridge missing", detail="Mission Control MCP bridge is not configured or discoverable.", severity="error", breakpoint="mcp.start", retryable=True, user_action_required=True, recommended_fix="Add the Mission Control MCP bridge to Codex and reload MCP configuration.", http_status=503),
    _entry("MC-MCP-TOOL-NOT-FOUND-001", family="MC-MCP", title="MCP tool not found", detail="The requested MCP tool was not found.", severity="error", breakpoint="mcp.tool_call", retryable=False, user_action_required=False, recommended_fix="Verify the Mission Control MCP tool catalog and plugin package.", http_status=404),
    _entry("MC-MCP-RESOURCE-NOT-FOUND-001", family="MC-MCP", title="MCP resource not found", detail="The requested MCP resource was not found.", severity="error", breakpoint="mcp.resource_read", retryable=False, user_action_required=False, recommended_fix="Verify the Mission Control MCP resource catalog and request URI.", http_status=404),
    _entry("MC-MCP-PROMPT-NOT-FOUND-001", family="MC-MCP", title="MCP prompt not found", detail="The requested MCP prompt was not found.", severity="error", breakpoint="mcp.prompt_render", retryable=False, user_action_required=False, recommended_fix="Verify the Mission Control prompt catalog and prompt name.", http_status=404),
    _entry("MC-MCP-HANDSHAKE-FAILED-001", family="MC-MCP", title="MCP handshake failed", detail="Mission Control MCP handshake failed.", severity="error", breakpoint="mcp.handshake", retryable=True, user_action_required=True, recommended_fix="Reload the MCP configuration and verify the local bridge process can start.", http_status=503),
    _entry("MC-PLUGIN-SKILL-MISSING-001", family="MC-PLUGIN", title="Plugin skill missing", detail="A required Mission Control skill file is missing.", severity="error", breakpoint="plugin.skill_discovery", retryable=False, user_action_required=True, recommended_fix="Restore the required Mission Control skill files and reload skill discovery.", http_status=500),
    _entry("MC-PLUGIN-PACKAGE-INVALID-001", family="MC-PLUGIN", title="Plugin package invalid", detail="Mission Control plugin package files are missing or invalid.", severity="error", breakpoint="plugin.package_validate", retryable=False, user_action_required=True, recommended_fix="Restore or rebuild the Mission Control plugin package.", http_status=500),
    _entry("MC-RUNNER-NONE-AVAILABLE-001", family="MC-RUNNER", title="No runners available", detail="Mission Control could not find any usable runner beyond dry-run mode.", severity="warning", breakpoint="runner.select", retryable=True, user_action_required=True, recommended_fix="Configure a local CLI runner or continue in dry-run mode.", http_status=503),
    _entry("MC-RUNNER-SELECTION-FAILED-001", family="MC-RUNNER", title="Runner selection failed", detail="Mission Control could not select a runner for the requested task.", severity="error", breakpoint="runner.select", retryable=True, user_action_required=False, recommended_fix="Inspect runner availability and selection policy, then try again.", http_status=500),
    _entry("MC-RUNNER-START-FAILED-001", family="MC-RUNNER", title="Runner start failed", detail="Mission Control could not start the selected runner.", severity="error", breakpoint="runner.start", retryable=True, user_action_required=False, recommended_fix="Inspect runner startup output and retry after fixing the local environment.", http_status=500),
    _entry("MC-RUNNER-TIMEOUT-001", family="MC-RUNNER", title="Runner timed out", detail="The selected runner timed out before completing its work.", severity="error", breakpoint="runner.fail", retryable=True, user_action_required=False, recommended_fix="Retry with a longer timeout or a different runner strategy.", http_status=504),
    _entry("MC-CODEX-CLI-MISSING-001", family="MC-CODEX", title="Codex CLI missing", detail="Codex CLI was not found on PATH.", severity="warning", breakpoint="codex_cli.detect", retryable=True, user_action_required=True, recommended_fix="Install Codex CLI or expose it on PATH, or continue with dry-run mode.", http_status=503),
    _entry("MC-CODEX-LOGIN-UNKNOWN-001", family="MC-CODEX", title="Codex login unknown", detail="Mission Control could not confirm Codex CLI login status.", severity="warning", breakpoint="codex_cli.login_status", retryable=True, user_action_required=True, recommended_fix="Run `codex login status` and sign in again if needed.", http_status=503),
    _entry("MC-CODEX-EXEC-FAILED-001", family="MC-CODEX", title="Codex CLI execution failed", detail="Codex CLI returned a failed execution state.", severity="error", breakpoint="codex_cli.exec", retryable=True, user_action_required=False, recommended_fix="Inspect the Codex CLI output and retry after fixing the local environment.", http_status=500),
    _entry("MC-OLLAMA-CLI-MISSING-001", family="MC-OLLAMA", title="Ollama CLI missing", detail="Ollama CLI was not found on PATH.", severity="warning", breakpoint="ollama.detect", retryable=True, user_action_required=True, recommended_fix="Install Ollama locally if you want to use a local model runner.", http_status=503),
    _entry("MC-OLLAMA-SERVER-OFFLINE-001", family="MC-OLLAMA", title="Ollama server offline", detail="Mission Control could not reach the local Ollama server.", severity="warning", breakpoint="ollama.server_check", retryable=True, user_action_required=True, recommended_fix="Start the local Ollama server and rerun the health check.", http_status=503),
    _entry("MC-OLLAMA-NO-MODELS-001", family="MC-OLLAMA", title="No Ollama models available", detail="Ollama is reachable but no models were detected.", severity="warning", breakpoint="ollama.model_list", retryable=True, user_action_required=True, recommended_fix="Pull or configure at least one local Ollama model before using the runner.", http_status=503),
    _entry("MC-CLAUDE-CLI-MISSING-001", family="MC-CLAUDE", title="Claude CLI missing", detail="Claude CLI was not found on PATH.", severity="warning", breakpoint="claude_cli.detect", retryable=True, user_action_required=True, recommended_fix="Install Claude CLI if you want Mission Control to use it.", http_status=503),
    _entry("MC-CLAUDE-AUTH-UNKNOWN-001", family="MC-CLAUDE", title="Claude auth unknown", detail="Mission Control could not confirm Claude CLI authentication state.", severity="warning", breakpoint="claude_cli.auth_status", retryable=True, user_action_required=True, recommended_fix="Finish Claude CLI authentication outside Mission Control, then retry.", http_status=503),
    _entry("MC-API-KEY-MISSING-001", family="MC-API", title="API key missing", detail="An API-backed runner was requested but no secure external credential was detected.", severity="warning", breakpoint="api_provider.auth_check", retryable=True, user_action_required=True, recommended_fix="Configure the API credential securely outside chat before enabling the runner.", http_status=503),
    _entry("MC-API-BILLING-WARNING-001", family="MC-API", title="API billing warning", detail="This runner may incur external API billing.", severity="warning", breakpoint="api_provider.detect", retryable=True, user_action_required=True, recommended_fix="Confirm that billed API use is intentional before enabling the runner.", http_status=409),
    _entry("MC-AUTH-BRIDGE-TOKEN-MISSING-001", family="MC-AUTH", title="Bridge token missing", detail="Mission Control bridge token is not configured.", severity="error", breakpoint="mcp.handshake", retryable=True, user_action_required=True, recommended_fix="Generate or restore the bridge token before calling protected routes.", http_status=503),
    _entry("MC-AUTH-BRIDGE-TOKEN-INVALID-001", family="MC-AUTH", title="Bridge token invalid", detail="The supplied Mission Control bridge token is missing or invalid.", severity="error", breakpoint="mcp.handshake", retryable=True, user_action_required=True, recommended_fix="Refresh the local bridge token and retry the request.", http_status=401),
    _entry("MC-SECRET-REDACTION-FAILED-001", family="MC-SECRET", title="Secret redaction failed", detail="Mission Control could not safely redact secret-like data.", severity="error", breakpoint="bridge.redact_output", retryable=False, user_action_required=False, recommended_fix="Inspect the redaction pipeline and block unsafe output until fixed.", http_status=500),
    _entry("MC-WORKSPACE-PATH-MISSING-001", family="MC-WORKSPACE", title="Workspace path missing", detail="Mission Control needs a workspace path or project reference to continue.", severity="error", breakpoint="workspace.attach", retryable=True, user_action_required=True, recommended_fix="Provide a valid workspace path or project identifier and retry.", http_status=400),
    _entry("MC-WORKSPACE-PERMISSION-DENIED-001", family="MC-WORKSPACE", title="Workspace permission denied", detail="Mission Control could not access the requested workspace path.", severity="error", breakpoint="workspace.attach", retryable=True, user_action_required=True, recommended_fix="Verify workspace path permissions and retry.", http_status=403),
    _entry("MC-WORKSPACE-AMBIGUOUS-001", family="MC-WORKSPACE", title="Workspace selection ambiguous", detail="Mission Control found multiple possible workspace targets and needs a decision.", severity="warning", breakpoint="workspace.detect_existing", retryable=True, user_action_required=True, recommended_fix="Choose the intended project before continuing.", http_status=409),
    _entry("MC-SCAN-READ-FAILED-001", family="MC-SCAN", title="Scan read failed", detail="Mission Control could not read a required part of the codebase during scan.", severity="error", breakpoint="workspace.read_only_scan", retryable=True, user_action_required=False, recommended_fix="Inspect file permissions and scan exclusions, then retry the scan.", http_status=500),
    _entry("MC-SCAN-TOO-LARGE-001", family="MC-SCAN", title="Scan scope too large", detail="Mission Control limited the codebase scan because the repo is too large for the requested scan depth.", severity="warning", breakpoint="workspace.read_only_scan", retryable=True, user_action_required=True, recommended_fix="Use a narrower scan target or accept a staged scan.", http_status=413),
    _entry("MC-SCAN-SECRET-LIKE-FILE-001", family="MC-SCAN", title="Secret-like file detected", detail="Mission Control found a file that appears to contain sensitive data during scan.", severity="warning", breakpoint="workspace.read_only_scan", retryable=True, user_action_required=True, recommended_fix="Review scan exclusions or keep the repo in read-only mode until the file is handled safely.", http_status=409),
    _entry("MC-SCAN-IGNORED-DIR-SKIPPED-001", family="MC-SCAN", title="Ignored directory skipped", detail="Mission Control skipped an ignored directory during scan.", severity="info", breakpoint="workspace.read_only_scan", retryable=True, user_action_required=False, recommended_fix="No action is required unless the skipped directory is relevant to the task.", http_status=200),
    _entry("MC-ORCH-SESSION-NOT-FOUND-001", family="MC-ORCH", title="Orchestration session not found", detail="Mission Control could not find the requested orchestration session.", severity="error", breakpoint="orchestration.create", retryable=False, user_action_required=False, recommended_fix="Verify the orchestration identifier and retry.", http_status=404),
    _entry("MC-ORCH-INVALID-STATE-001", family="MC-ORCH", title="Invalid orchestration state", detail="Mission Control cannot continue because the orchestration is in an invalid state.", severity="error", breakpoint="orchestration.fail", retryable=False, user_action_required=False, recommended_fix="Inspect orchestration state and recover or recreate the session.", http_status=409),
    _entry("MC-ORCH-START-FAILED-001", family="MC-ORCH", title="Orchestration start failed", detail="Mission Control could not start the requested orchestration.", severity="error", breakpoint="orchestration.create", retryable=True, user_action_required=False, recommended_fix="Retry after verifying workspace attach, runner selection, and daemon health.", http_status=500),
    _entry("MC-ORCH-RESUME-FAILED-001", family="MC-ORCH", title="Orchestration resume failed", detail="Mission Control could not resume the requested orchestration.", severity="error", breakpoint="orchestration.resume_after_decision", retryable=True, user_action_required=False, recommended_fix="Check the orchestration state and pending decisions before retrying.", http_status=409),
    _entry("MC-MANAGER-PLAN-FAILED-001", family="MC-MANAGER", title="Manager plan failed", detail="Mission Control Manager could not generate a usable plan.", severity="error", breakpoint="manager.generate_plan", retryable=True, user_action_required=False, recommended_fix="Retry planning after narrowing the request or refreshing project context.", http_status=500),
    _entry("MC-MANAGER-OUTPUT-INVALID-001", family="MC-MANAGER", title="Manager output invalid", detail="Mission Control Manager returned output that could not be applied safely.", severity="error", breakpoint="manager.consume_agent_report", retryable=True, user_action_required=False, recommended_fix="Retry the manager step after validating the expected output shape.", http_status=500),
    _entry("MC-MANAGER-QUESTION-FAILED-001", family="MC-MANAGER", title="Manager question failed", detail="Mission Control could not create or apply a manager question.", severity="error", breakpoint="manager.create_pending_decision", retryable=True, user_action_required=False, recommended_fix="Retry the question flow after inspecting the manager context.", http_status=500),
    _entry("MC-AGENT-START-FAILED-001", family="MC-AGENT", title="Agent start failed", detail="Mission Control could not start a worker agent.", severity="error", breakpoint="runner.start", retryable=True, user_action_required=False, recommended_fix="Retry the agent launch after validating runner availability.", http_status=500),
    _entry("MC-AGENT-REPORT-INVALID-001", family="MC-AGENT", title="Agent report invalid", detail="Mission Control received an invalid worker report.", severity="error", breakpoint="manager.consume_agent_report", retryable=True, user_action_required=False, recommended_fix="Retry after validating the expected agent report format.", http_status=500),
    _entry("MC-AGENT-STUCK-001", family="MC-AGENT", title="Agent appears stuck", detail="Mission Control has not observed useful progress from a worker agent.", severity="warning", breakpoint="runner.stream_events", retryable=True, user_action_required=False, recommended_fix="Retry, reassign, or pause the affected agent after reviewing recent events.", http_status=504),
    _entry("MC-SUBAGENT-BURST-DENIED-001", family="MC-SUBAGENT", title="Subagent burst denied", detail="Mission Control did not approve the requested subagent burst.", severity="warning", breakpoint="subagent_burst.approve", retryable=False, user_action_required=True, recommended_fix="Review the burst recommendation and approval threshold before trying again.", http_status=403),
    _entry("MC-SUBAGENT-RESULT-INVALID-001", family="MC-SUBAGENT", title="Subagent result invalid", detail="Mission Control could not accept a subagent burst result.", severity="error", breakpoint="subagent_burst.ingest_result", retryable=True, user_action_required=False, recommended_fix="Validate the expected result shape and retry the subagent workflow.", http_status=500),
    _entry("MC-SUBAGENT-TOO-MANY-001", family="MC-SUBAGENT", title="Too many subagents requested", detail="The requested subagent burst exceeds the configured safety limit.", severity="warning", breakpoint="subagent_burst.plan", retryable=True, user_action_required=True, recommended_fix="Lower the requested burst size or request explicit approval for a larger burst.", http_status=409),
    _entry("MC-DECISION-NOT-FOUND-001", family="MC-DECISION", title="Pending decision not found", detail="Mission Control could not find the requested pending decision.", severity="error", breakpoint="decision.answer", retryable=False, user_action_required=False, recommended_fix="Refresh the pending decision list and retry with a valid decision identifier.", http_status=404),
    _entry("MC-DECISION-INVALID-OPTION-001", family="MC-DECISION", title="Invalid pending decision option", detail="The selected option is not allowed for this pending decision.", severity="error", breakpoint="decision.validate_option", retryable=False, user_action_required=True, recommended_fix="Choose one of the allowed options returned by Mission Control.", http_status=400),
    _entry("MC-DECISION-EXPIRED-001", family="MC-DECISION", title="Pending decision expired", detail="The pending decision is no longer actionable.", severity="error", breakpoint="decision.expire", retryable=False, user_action_required=False, recommended_fix="Refresh the decision state and request a new decision if needed.", http_status=409),
    _entry("MC-DECISION-HIGH-RISK-BLOCKED-001", family="MC-DECISION", title="High-risk decision blocked", detail="Mission Control blocked a high-risk action pending explicit approval.", severity="warning", breakpoint="decision.apply", retryable=True, user_action_required=True, recommended_fix="Review the approval request and answer it explicitly before continuing.", http_status=403),
    _entry("MC-BRIDGE-FORMAT-FAILED-001", family="MC-BRIDGE", title="Bridge format failed", detail="Mission Control could not format a bridge-safe summary.", severity="error", breakpoint="bridge.format_status", retryable=True, user_action_required=False, recommended_fix="Retry the bridge formatting step after validating the payload.", http_status=500),
    _entry("MC-BRIDGE-REDACTION-FAILED-001", family="MC-BRIDGE", title="Bridge redaction failed", detail="Mission Control could not safely redact bridge output.", severity="error", breakpoint="bridge.redact_output", retryable=False, user_action_required=False, recommended_fix="Inspect the redaction layer and block the unsafe output until fixed.", http_status=500),
    _entry("MC-BRIDGE-MISSING-FALLBACK-001", family="MC-BRIDGE", title="Bridge fallback missing", detail="Mission Control could not provide a fallback chat summary.", severity="error", breakpoint="bridge.format_status", retryable=True, user_action_required=False, recommended_fix="Ensure that every bridge message includes a safe fallback markdown summary.", http_status=500),
    _entry("MC-HANDOFF-NOT-READY-001", family="MC-HANDOFF", title="Handoff not ready", detail="Mission Control does not have a handoff ready yet.", severity="warning", breakpoint="handoff.generate", retryable=True, user_action_required=False, recommended_fix="Wait for Mission Control to finish the current iteration and retry the handoff request.", http_status=409),
    _entry("MC-HANDOFF-EVIDENCE-MISSING-001", family="MC-HANDOFF", title="Handoff evidence missing", detail="Mission Control cannot support one or more handoff claims with recorded evidence.", severity="warning", breakpoint="handoff.validate_claims", retryable=True, user_action_required=True, recommended_fix="Run or record the missing validation evidence before treating the handoff as complete.", http_status=409),
    _entry("MC-HANDOFF-RENDER-FAILED-001", family="MC-HANDOFF", title="Handoff render failed", detail="Mission Control could not render the handoff summary.", severity="error", breakpoint="handoff.render_chat_summary", retryable=True, user_action_required=False, recommended_fix="Retry handoff rendering after validating the handoff payload.", http_status=500),
    _entry("MC-VALIDATION-NOT-RUN-001", family="MC-VALIDATION", title="Validation not run", detail="Mission Control could not confirm that the requested validation step was run.", severity="warning", breakpoint="handoff.collect_evidence", retryable=True, user_action_required=True, recommended_fix="Run the validation step or mark the handoff as lacking validation evidence.", http_status=409),
    _entry("MC-VALIDATION-FAILED-001", family="MC-VALIDATION", title="Validation failed", detail="A requested validation step failed.", severity="error", breakpoint="handoff.collect_evidence", retryable=True, user_action_required=False, recommended_fix="Inspect the failing validation step, fix the issue, and rerun validation.", http_status=422),
    _entry("MC-VALIDATION-COMMAND-DENIED-001", family="MC-VALIDATION", title="Validation command denied", detail="Mission Control could not run validation because the command was denied by policy or approval state.", severity="warning", breakpoint="decision.apply", retryable=True, user_action_required=True, recommended_fix="Approve the validation command or adjust policy before retrying.", http_status=403),
    _entry("MC-SECURITY-POLICY-BLOCKED-001", family="MC-SECURITY", title="Security policy blocked action", detail="Mission Control blocked the requested action because of the active security policy.", severity="warning", breakpoint="decision.apply", retryable=True, user_action_required=True, recommended_fix="Review the active security policy or answer the required approval request.", http_status=403),
    _entry("MC-SECURITY-SECRET-DETECTED-001", family="MC-SECURITY", title="Secret-like data detected", detail="Mission Control found secret-like data in user-facing output or scan content.", severity="warning", breakpoint="bridge.redact_output", retryable=True, user_action_required=False, recommended_fix="Keep the output redacted and review the source before sharing it further.", http_status=409),
    _entry("MC-STORAGE-DB-UNAVAILABLE-001", family="MC-STORAGE", title="Database unavailable", detail="Mission Control could not query the local SQLite database.", severity="error", breakpoint="bootstrap.health_check", retryable=True, user_action_required=True, recommended_fix="Inspect the runtime SQLite file, local permissions, and backend startup state.", http_status=503),
    _entry("MC-STORAGE-RUNTIME-WRITE-FAILED-001", family="MC-STORAGE", title="Runtime write failed", detail="Mission Control could not write to the runtime directory.", severity="error", breakpoint="diagnostics.write_report", retryable=True, user_action_required=True, recommended_fix="Fix local filesystem permissions for the runtime directory and retry.", http_status=500),
    _entry("MC-DIAGNOSTIC-RUN-FAILED-001", family="MC-DIAGNOSTIC", title="Diagnostic run failed", detail="Mission Control could not complete the requested diagnostic run.", severity="error", breakpoint="diagnostics.run", retryable=True, user_action_required=False, recommended_fix="Retry diagnostics after verifying daemon health and runtime writability.", http_status=500),
    _entry("MC-DIAGNOSTIC-REPORT-WRITE-FAILED-001", family="MC-DIAGNOSTIC", title="Diagnostic report write failed", detail="Mission Control could not write the diagnostic report.", severity="error", breakpoint="diagnostics.write_report", retryable=True, user_action_required=True, recommended_fix="Verify that the diagnostics directory exists and is writable.", http_status=500),
    _entry("MC-NETWORK-LOCALHOST-UNREACHABLE-001", family="MC-NETWORK", title="Localhost unreachable", detail="Mission Control could not reach the expected local endpoint.", severity="error", breakpoint="daemon.health_check", retryable=True, user_action_required=True, recommended_fix="Verify that the daemon is bound to localhost and the endpoint is reachable.", http_status=503),
    _entry("MC-NETWORK-PORT-CHECK-FAILED-001", family="MC-NETWORK", title="Port check failed", detail="Mission Control could not confirm the expected local port state.", severity="warning", breakpoint="daemon.port_bind", retryable=True, user_action_required=False, recommended_fix="Retry the local port check or inspect the daemon configuration.", http_status=500),
    _entry("MC-DOCS-LINK-CHECK-FAILED-001", family="MC-DOCS", title="Documentation link check failed", detail="Mission Control documentation validation found a broken or invalid link.", severity="warning", breakpoint="diagnostics.run", retryable=True, user_action_required=False, recommended_fix="Run the documentation checker and repair the reported links.", http_status=500),
    _entry("MC-UNKNOWN-UNEXPECTED-001", family="MC-UNKNOWN", title="Unexpected Mission Control error", detail="Mission Control encountered an unexpected error.", severity="error", breakpoint="diagnostics.run", retryable=False, user_action_required=False, recommended_fix="Inspect the correlation ID and internal logs, then retry if the issue was transient.", http_status=500),
]


ERROR_REGISTRY: dict[str, ErrorDefinition] = {item.code: item for item in _DEFINITIONS}


def get_error_definition(code: str) -> ErrorDefinition:
    try:
        return ERROR_REGISTRY[code]
    except KeyError as exc:
        raise KeyError(f"Unknown Mission Control error code: {code}") from exc


def iter_error_definitions() -> tuple[ErrorDefinition, ...]:
    return tuple(ERROR_REGISTRY.values())
